package nexus;

import nexus.commands.Command;
import nexus.exception.NexusException;
import nexus.parser.Parser;
import nexus.storage.Storage;
import nexus.tasks.TaskList;
import nexus.ui.Ui;

/**
 * Main application class for Nexus.
 */
public class Nexus {
    private static final String DATA_FILE_PATH = "data/databank.txt";

    private final Storage storage;
    private TaskList tasks;
    private final Ui ui;
    private String commandType;
    private String corruptedDataPrompt = "";

    /**
     * Constructs a Nexus application with the specified data file path.
     * @param filePath The path to the data file.
     */
    public Nexus(String filePath) {
        this.ui = new Ui();
        this.storage = new Storage(filePath);
        try {
            this.tasks = new TaskList(this.storage.loadTasks());
        } catch (NexusException e) {
            this.storage.wipeData();
            this.tasks = new TaskList();
            this.corruptedDataPrompt = "[NEXUS]: Databank corrupted. To avoid issues, existing data has been wiped.\n";
        }
    }

    /**
     * Runs the Nexus application, handling user commands and interactions.
     */
    public void run() {
        boolean isExit = false;

        while (!isExit) {
            try {
                String fullCommand = ui.readCommand();

                Command cmd = Parser.parse(fullCommand);

                cmd.run(tasks, ui, storage);

                isExit = cmd.isExit();
            } catch (NexusException e) {
                ui.printError(e.getMessage());
            }
        }
    }

    /**
     * Main entry point for the Nexus application.
     * @param args Command-line arguments (not used).
     */
    public static void main(String[] args) throws NexusException {
        new Nexus(DATA_FILE_PATH).run();
    }

    /**
     * Returns a response to the given user input.
     * @param input The user input to process.
     * @return A string response generated by the Nexus application.
     */
    public String getResponse(String input) throws NexusException {
        Command cmd = Parser.parse(input);
        this.commandType = cmd.getName();

        return cmd.run(tasks, ui, storage);
    }

    /**
     * Returns the type of the last executed command.
     * @return The name of the last executed command.
     */
    public String getCommandType() {
        return this.commandType;
    }
    /**
     * Returns the prompt for corrupted data handling.
     * @return The prompt message for corrupted data.
     */
    public String getCorruptedDataPrompt() {
        return corruptedDataPrompt;
    }
}
