package nexus;

import nexus.commands.Command;
import nexus.exception.NexusException;
import nexus.parser.Parser;
import nexus.storage.Storage;
import nexus.tasks.TaskList;
import nexus.ui.Ui;

/**
 * Main application class for Nexus.
 */
public class Nexus {
    private static final String DATA_FILE_PATH = "data/databank.txt";

    private final Storage storage;
    private TaskList tasks;
    private final Ui ui;
    private String commandType;

    /**
     * Constructs a Nexus application with the specified data file path.
     * @param filePath The path to the data file.
     */
    public Nexus(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        try {
            tasks = new TaskList(storage.loadTasks());
        } catch (NexusException e) {
            ui.printError(e.getMessage());
            tasks = new TaskList();
        }
    }

    /**
     * Runs the Nexus application, handling user commands and interactions.
     */
    public void run() {
        ui.printGreeting();
        boolean isExit = false;

        while (!isExit) {
            try {
                String fullCommand = ui.readCommand();

                Command cmd = Parser.parse(fullCommand);

                cmd.run(tasks, ui, storage);

                isExit = cmd.isExit();
            } catch (NexusException e) {
                ui.printError(e.getMessage());
            }
        }
    }

    /**
     * Main entry point for the Nexus application.
     * @param args Command-line arguments (not used).
     */
    public static void main(String[] args) {
        new Nexus(DATA_FILE_PATH).run();
    }

    /**
     * Returns a response to the given user input.
     * @param input The user input to process.
     * @return A string response generated by the Nexus application.
     */
    public String getResponse(String input) {
        try {
            Command cmd = Parser.parse(input);
            this.commandType = cmd.getName();

            return cmd.run(tasks, ui, storage);

        } catch (NexusException e) {
            return ui.printError(e.getMessage());
        }
    }

    /**
     * Returns the type of the last executed command.
     * @return The name of the last executed command.
     */
    public String getCommandType() {
        return this.commandType;
    }
}
